$(document).ready(function(){
var links = $(".links");
var information = $(".information");
    $("a[href='#home']").click(function(){
    	information.fadeOut(700);
    	$(".links").delay(700).fadeIn(700);
});
	$("a[href='#KyoAni']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#KyoAni").delay(700).fadeIn(700);
});
	$("a[href='#A-1_Pictures']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#A-1_Pictures").delay(700).fadeIn(700);
});
	$("a[href='#JCStaff']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#JCStaff").delay(700).fadeIn(700);
});
	$("a[href='#Bones']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Bones").delay(700).fadeIn(700);
});
	$("a[href='#Shaft']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Shaft").delay(700).fadeIn(700);
});
	$("a[href='#Sunrise']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Sunrise").delay(700).fadeIn(700);
});
	$("a[href='#Mad_House']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Mad_House").delay(700).fadeIn(700);
});
	$("a[href='#Doga_Kobo']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Doga_Kobo").delay(700).fadeIn(700);
});
	$("a[href='#Gainax']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Gainax").delay(700).fadeIn(700);
});
	$("a[href='#ufotable']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#ufotable").delay(700).fadeIn(700);
});
	$("a[href='#WIT_Studio']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#WIT_Studio").delay(700).fadeIn(700);
});
	$("a[href='#TRIGGER']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#TRIGGER").delay(700).fadeIn(700);
});
	$("a[href='#Lerche']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Lerche").delay(700).fadeIn(700);
});
	$("a[href='#PAWorks']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#PAWorks").delay(700).fadeIn(700);
});	
	$("a[href='#Production_IG']").click(function(){
		information.fadeOut(700);
		links.fadeOut(700);
		$("#Production_IG").delay(700).fadeIn(700);
});
});